%% This is because I first simulated everything with unrestriced joints and without writing it in the logs!
% (Whether joints are restricted or not provide whole different results)
% logNamesVec = {'RRT.log', ...
%                'RRTwrapped.log', ...
%                'EST.log', ...
%                'ESTwrapped.log', ...
%                'PRMstar.log', ...
%                'RRTCstar.log', ...
%                'RRTC.log', ...
%                'RRTCwrapped.log', ...
%                'TRRTwrapped.log', ...
%                'TRRT.log'};
for k=1:numel(logNamesVec) %all planners
    fileName = string(logNamesVec(k));
    
    %% read each line
    fileID = fopen(fileName,'r');
    tline = fgetl(fileID);
    toInsert = cell(0,1);
    while ischar(tline)
        toInsert{end+1,1} = tline;
        tline = fgetl(fileID);
    end
    fclose(fileID);
    toInsert = string(toInsert);
end